# .travis.yml - 2013-10-12 10:10
#
# Copyright (c) 2013 Paul Houghton <paul4hough@gmail.com>
# ping travis

language: c
notifications:
  email:
    - paul4hough@gmail.com

install:
  - sudo apt-get update
#  - bash setup-product.bash

before_script:
  - uname -a
  - ls -al
  - pwd
  - env
  - sudo env

script:
#  - tests/runtests.bash
   - bash tests/TravisDebug.bash
   
after_script:
  - find . -type f -ls
