# .travis.yml - 2013-10-12 10:10
#
# Copyright (c) 2013 Paul Houghton <paul4hough@gmail.com>
# ping travis

language: c
notifications:
  email:
    - paul4hough@gmail.com

before_script:
  - uname -a
  - ls -al
  - pwd
  - env
  - sudo env
  - bash setup-product.bash

script:
  - tests/runtests.bash

after_script:
  - which puppet
  - puppet --version
  - find . -type f -ls
