# .travis.yml - 2013-10-12 10:10
#
# Copyright (c) 2013 Paul Houghton <paul4hough@gmail.com>

language: c
notifications:
  email:
    - paul4hough@gmail.com

before_script:
  - uname -a
  - ls -al
  - pwd
  - env
  - DEBUG=1 bash setup-product.bash
  - env

script:
  - DEBUG=1 tests/runtests.bash

after_script:
  - which puppet
  - puppet --version
  - find . -type f -ls
